language: java
sudo: false
idst: bionic
jdk:
  - openjdk8
  - openjdk10
matrix:
  jobs:
    - jdk: openjdk10
      arch: ppc64le
      dist: bionic
    - jdk: openjdk8
      arch: ppc64le
      dist: bionic
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
