language: java
dist: xenial
sudo: required

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - jdk: openjdk8
# ppc64le support code
    - os: linux
      arch: ppc64le
      jdk: openjdk8
      addons:
        apt:
          packages:
          - maven
      
script:
  - mvn -V --no-transfer-progress clean test
after_success:
  - mvn -V --no-transfer-progress clean cobertura:cobertura coveralls:report
