language: java
dist: xenial
sudo: required
arch:
  - amd64
  - ppc64le
  
cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    jdk:
    - openjdk15    
    
script:
  - mvn -V --no-transfer-progress clean test
after_success:
  - mvn -V --no-transfer-progress clean cobertura:cobertura coveralls:report
