language: java
dist: xenial
sudo: required

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
# ppc64le support code
  - os: linux
    arch: ppc64le
    jdk: openjdk8
    addons:
      apt:
        packages:
        - maven
jdk:
- openjdk8     

script:
  - mvn -V --no-transfer-progress clean test
after_success:
  - mvn -V --no-transfer-progress clean cobertura:cobertura coveralls:report
