language: java
dist: xenial
sudo: required
arch:
  - amd64
  - ppc64le

jobs:
  include:
    jdk:
    - openjdk15    
cache:
  directories:
    - $HOME/.m2
    
script:
  - mvn -V --no-transfer-progress clean -Denforcer.skip=true test
after_success:
  - mvn -V --no-transfer-progress clean cobertura:cobertura coveralls:report
